# This file was generated by GoReleaser. DO NOT EDIT.
cask "gumroad" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v#{version}/gumroad-cli_darwin_amd64.tar.gz",
        verified: "github.com/antiwork/gumroad-cli/"
      sha256 "340d4f9894d6f9da535e4fbab2b1eb88a74e7ee1bdeda362553f945fdde075e3"
    end
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v#{version}/gumroad-cli_darwin_arm64.tar.gz",
        verified: "github.com/antiwork/gumroad-cli/"
      sha256 "5bf4ef30b9192bb6357d9ef18cb9f63373bf49d81e306af0f028cedaeb0a95ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v#{version}/gumroad-cli_linux_amd64.tar.gz",
        verified: "github.com/antiwork/gumroad-cli/"
      sha256 "24d40748e2f714071bcc87188a58c9b4945a0ebc75b99f29e09b2526e669dc11"
    end
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v#{version}/gumroad-cli_linux_arm64.tar.gz",
        verified: "github.com/antiwork/gumroad-cli/"
      sha256 "f63976b1954d7375eb9f23e725365c1ee725afa1583c36fae2d164fbaf2b118e"
    end
  end

  name "gumroad"
  desc "CLI for the Gumroad API"
  homepage "https://gumroad.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gumroad"
  manpage "man/gumroad-auth-login.1"
  manpage "man/gumroad-auth-logout.1"
  manpage "man/gumroad-auth-status.1"
  manpage "man/gumroad-auth.1"
  manpage "man/gumroad-completion.1"
  manpage "man/gumroad-custom-fields-create.1"
  manpage "man/gumroad-custom-fields-delete.1"
  manpage "man/gumroad-custom-fields-list.1"
  manpage "man/gumroad-custom-fields-update.1"
  manpage "man/gumroad-custom-fields.1"
  manpage "man/gumroad-licenses-decrement.1"
  manpage "man/gumroad-licenses-disable.1"
  manpage "man/gumroad-licenses-enable.1"
  manpage "man/gumroad-licenses-rotate.1"
  manpage "man/gumroad-licenses-verify.1"
  manpage "man/gumroad-licenses.1"
  manpage "man/gumroad-offer-codes-create.1"
  manpage "man/gumroad-offer-codes-delete.1"
  manpage "man/gumroad-offer-codes-list.1"
  manpage "man/gumroad-offer-codes-update.1"
  manpage "man/gumroad-offer-codes-view.1"
  manpage "man/gumroad-offer-codes.1"
  manpage "man/gumroad-payouts-list.1"
  manpage "man/gumroad-payouts-upcoming.1"
  manpage "man/gumroad-payouts-view.1"
  manpage "man/gumroad-payouts.1"
  manpage "man/gumroad-products-create.1"
  manpage "man/gumroad-products-delete.1"
  manpage "man/gumroad-products-list.1"
  manpage "man/gumroad-products-publish.1"
  manpage "man/gumroad-products-skus.1"
  manpage "man/gumroad-products-unpublish.1"
  manpage "man/gumroad-products-update.1"
  manpage "man/gumroad-products-view.1"
  manpage "man/gumroad-products.1"
  manpage "man/gumroad-sales-list.1"
  manpage "man/gumroad-sales-refund.1"
  manpage "man/gumroad-sales-resend-receipt.1"
  manpage "man/gumroad-sales-ship.1"
  manpage "man/gumroad-sales-view.1"
  manpage "man/gumroad-sales.1"
  manpage "man/gumroad-skill-install.1"
  manpage "man/gumroad-skill.1"
  manpage "man/gumroad-subscribers-list.1"
  manpage "man/gumroad-subscribers-view.1"
  manpage "man/gumroad-subscribers.1"
  manpage "man/gumroad-user.1"
  manpage "man/gumroad-variant-categories-create.1"
  manpage "man/gumroad-variant-categories-delete.1"
  manpage "man/gumroad-variant-categories-list.1"
  manpage "man/gumroad-variant-categories-update.1"
  manpage "man/gumroad-variant-categories-view.1"
  manpage "man/gumroad-variant-categories.1"
  manpage "man/gumroad-variants-create.1"
  manpage "man/gumroad-variants-delete.1"
  manpage "man/gumroad-variants-list.1"
  manpage "man/gumroad-variants-update.1"
  manpage "man/gumroad-variants-view.1"
  manpage "man/gumroad-variants.1"
  manpage "man/gumroad-webhooks-create.1"
  manpage "man/gumroad-webhooks-delete.1"
  manpage "man/gumroad-webhooks-list.1"
  manpage "man/gumroad-webhooks.1"
  manpage "man/gumroad.1"
  generate_completions_from_executable "gumroad", "completion",
    shell_parameter_format: :cobra

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gumroad"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    `gumroad` is currently distributed as an unsigned, non-notarized binary.
    On macOS, this cask removes the quarantine bit after install.
    If Gatekeeper still blocks execution, run:
      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/gumroad"
  EOS
end
