# This file is generated by script/render-homebrew-formula.sh. DO NOT EDIT.
class Gumroad < Formula
  desc "CLI for the Gumroad API"
  homepage "https://github.com/antiwork/gumroad-cli"
  version "2026.09.23"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260923.0/gumroad-cli_darwin_arm64.tar.gz"
      sha256 "0c6107d8fa97c5c8f8f76fd3e487c1e305e708dca5b35883de371c27a8a6ef92"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260923.0/gumroad-cli_darwin_amd64.tar.gz"
      sha256 "b3d43fc80894205bcfd5441d9f56f9d6ee364acfbaa54648873030f0c1c2f166"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260923.0/gumroad-cli_linux_arm64.tar.gz"
      sha256 "816f0647408cd20cbb008a9cc739fc791f03c96e2516bae5792add53d23a3caa"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260923.0/gumroad-cli_linux_amd64.tar.gz"
      sha256 "3943881d160018549129d0291205382d1b27ea2c0c1bb4354c00c05e5d965f85"
    end
  end

  def install
    bin.install "gumroad"
    man1.install Dir["man/*.1"]
    generate_completions_from_executable(bin/"gumroad", "completion")
    (pwsh_completion/"gumroad.ps1").write Utils.safe_popen_read(bin/"gumroad", "completion", "powershell")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gumroad --version")
  end
end
