# This file is generated by script/render-homebrew-formula.sh. DO NOT EDIT.
class Gumroad < Formula
  desc "CLI for the Gumroad API"
  homepage "https://github.com/antiwork/gumroad-cli"
  version "2026.06.19"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260619.0/gumroad-cli_darwin_arm64.tar.gz"
      sha256 "94b1d12feb2bbeb873b8f5be095eaaa832460e448dd64c35cfaf5a1e0828be55"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260619.0/gumroad-cli_darwin_amd64.tar.gz"
      sha256 "ccc168a4b3f7b0f2f32d1806ae6cdd10569a0af77295ffac2da5345cfc019f81"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260619.0/gumroad-cli_linux_arm64.tar.gz"
      sha256 "b38e2613927a28adcdf6157b13e3142209e83ccaeeb926144c8102c91b2f5ad9"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260619.0/gumroad-cli_linux_amd64.tar.gz"
      sha256 "6d1310fe4091d281b8e8447d56b7b7ddae42a5f6c390991a5eff9ac6a517f457"
    end
  end

  def install
    bin.install "gumroad"
    man1.install Dir["man/*.1"]
    generate_completions_from_executable(bin/"gumroad", "completion")
    (pwsh_completion/"gumroad.ps1").write Utils.safe_popen_read(bin/"gumroad", "completion", "powershell")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gumroad --version")
  end
end
