# This file is generated by script/render-homebrew-formula.sh. DO NOT EDIT.
class Gumroad < Formula
  desc "CLI for the Gumroad API"
  homepage "https://github.com/antiwork/gumroad-cli"
  version "2026.06.22"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260622.0/gumroad-cli_darwin_arm64.tar.gz"
      sha256 "2fe090defba7eed404bfb0eadbff4810b07eff0b63460a644b697bce6fb117d3"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260622.0/gumroad-cli_darwin_amd64.tar.gz"
      sha256 "a6223d98667b560900eb0ce9325ed5ce9b5420ada09fcf5c2e899d668ed8aa70"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260622.0/gumroad-cli_linux_arm64.tar.gz"
      sha256 "a5cedb44a2d82d10f23cfb402f464a2c67f49cb6cf7e83a5042a85f126eb3b23"
    end
    on_intel do
      url "https://github.com/antiwork/gumroad-cli/releases/download/v0.20260622.0/gumroad-cli_linux_amd64.tar.gz"
      sha256 "7bdc35f1b9d3ef43d6337f9aa8de9b86d5f643ebb030bd012eeb9f2177fc908f"
    end
  end

  def install
    bin.install "gumroad"
    man1.install Dir["man/*.1"]
    generate_completions_from_executable(bin/"gumroad", "completion")
    (pwsh_completion/"gumroad.ps1").write Utils.safe_popen_read(bin/"gumroad", "completion", "powershell")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gumroad --version")
  end
end
